version: '6.9'
services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  webapp:
    build: .
    container_name: kartverketregister
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=testink;User=root;Password=mysecretpassword;"

volumes:
  db_data:
