version: '6.9'
services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  webapp:
    build: .
    container_name: kartverketregister
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=testink;User=root;Password=mysecretpassword;"
      DATABASE_IP: mariadb
      DATABASE_PORT: 3306

volumes:
  db_data:
